### ISSUE TITLE
SSO across multiple servers

### ISSUE THREAD

**Issue by alexanderfrankel** [wardencommunity/sinatra_warden#20]
@jsmestad I have a Rails app that handles all of our authentication today using sessions stored in cookies. Upon every request, the cookie is sent back to the Rails app, decrypted using devise, and authenticated.

I have a separate sinatra app under the same tld that needs to authenticate each incoming request. I would like to send the same cookie generated from the Rails app mentioned above to this separate sinatra app to authenticate. Can I use sintatra_warden to do so?

I realize I will need a shared secret between the two apps...

**Comment by jsmestad** [comment]
Yes that is technically possible. This library provides a helpers and hooks for using Warden in Sinatra. If you can overcome of the technical and security concerns by doing something like this, there is nothing inside of this library that should stand in your way.
